### ISSUE TITLE
`Cannot use import statement outside a module`

### ISSUE THREAD

**Issue by mikehobi** [makeup/makeup-js#172]
-  `"@marko/run": "^0.4.3"`
- `"@ebay/ebayui-core": "^13.5.0"`
- `"@ebay/skin": "^17.5.0"`

When using `<ebay-lightbox-dialog>`, I get an error from `makeup-screenreader-trap`. This is on a fresh marko run ts project with skin and ebayui-core.

```/Users/mhobizal/exp/pdf-preview/node_modules/makeup-screenreader-trap/dist/mjs/index.js:1
import * as util from "./util.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at internalCompileFunction (node:internal/vm:76:18)
    at wrapSafe (node:internal/modules/cjs/loader:1283:20)
    at Module._compile (node:internal/modules/cjs/loader:1328:27)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:203:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async ModuleLoader.import (node:internal/modules/esm/loader:337:24)
    at async nodeImport (file:///Users/mhobizal/exp/pdf-preview/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56275:17)
    at async ssrImport (file:///Users/mhobizal/exp/pdf-preview/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56177:24)
    at async eval (/Users/mhobizal/exp/pdf-preview/node_modules/@ebay/ebayui-core/dist/components/components/ebay-dialog-base/component.js:6:31)
    at async instantiateModule (file:///Users/mhobizal/exp/pdf-preview/node_modules/vite/dist/node/chunks/dep-DEPSZ3SS.js:56237:9)```
    
   ### Workaround
   
Renaming `./dist/mjs/index.js` -> `./dist/mjs/index.mjs` and updating the file names in each module's `package.json` fixes the issue

**Comment by ianmcburnie** [comment]
I'll do this along with #167 and publish new minor versions.

**Comment by ianmcburnie** [comment]
Done: https://github.com/makeup/makeup-js/commit/b97045a41cccc7b21acc4b03271b14d728e0b87b

**Comment by vwong** [comment]
fyi @ianmcburnie, these additional files you added are not available when installed from npm.

**Comment by ianmcburnie** [comment]
@vwong Thank you for spotting this. It looks like I overlooked updating the files section: https://github.com/makeup/makeup-js/blob/master/packages/core/makeup-active-descendant/package.json#L32

Reopening,
